---
- hosts: all
  become: yes
  tasks:
  - name: update packages
    apt:
     update_cache: yes
     state: present
  - name: install apache2
    apt:
     name: apache2
     state: present
  - name: restart apache2 after installation
    service:
     name: apache2
     state: restarted
  - name: install PHP packages
    apt:
     name: "{{ item }}"
     state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
  - name: restart the apache2
    service:
     name: apache2
     state: restarted